chore: ci fixing #7 try, with auto detect & update cargo version in ci env

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -122,10 +122,29 @@ jobs:
           submodules: recursive
       - name: Install Rust non-interactively if not already installed
         if: ${{ matrix.container }}
+#        run: |
+#          if ! command -v cargo > /dev/null 2>&1; then
+#            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+#            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
+#          fi
         run: |
-          if ! command -v cargo > /dev/null 2>&1; then
-            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
+          REQUIRED_RUST_VERSION=$(grep '^rust-version' Cargo.toml | awk -F'"' '{print $2}')
+          if command -v cargo >/dev/null 2>&1; then
+              INSTALLED_RUST_VERSION=$(rustc --version | awk '{print $2}')
+              if [ "$(printf '%s\n' "$REQUIRED_RUST_VERSION" "$INSTALLED_RUST_VERSION" | sort -V | head -n1)" = "$INSTALLED_RUST_VERSION" ]; then
+                  echo "Installed Rust ($INSTALLED_RUST_VERSION) is older than required ($REQUIRED_RUST_VERSION), installing rustup..."
+                  INSTALL=true
+              else
+                  echo "Installed Rust ($INSTALLED_RUST_VERSION) meets required version ($REQUIRED_RUST_VERSION)."
+                  INSTALL=false
+              fi
+          else
+              echo "Cargo not found, installing rustup..."
+              INSTALL=true
+          fi
+          if [ "$INSTALL" = true ]; then
+              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain "$REQUIRED_RUST_VERSION"
+              echo "$HOME/.cargo/bin" >> $GITHUB_PATH
           fi
       - name: Install dist
         run: ${{ matrix.install_dist.run }}
